dataRetentionDays: 30
# mongoDbUri: mongodb://172.16.0.113:27017/?maxPoolSize=20 
mongodb:
  enabled: true
  uri: mongodb://localhost:27017
logCleanPaths:
  - /Users/dayong/myspace/mywork/rainbow-api/.log
  - /Users/dayong/myspace/mywork/rainbow-settle/server/.log